### ISSUE TITLE
wiki: add how to submit gnu parallel jobs with slurm (e.g. Cori) 

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/xolotl#104]
Short examples in 
https://fusionga-my.sharepoint.com/:f:/r/personal/guterlj_fusion_gat_com/Documents/PSI2-SciDAC/Xolotl/UQ/gnu_parallel/test_parallel?csf=1&web=1&e=CfEDP0

**Comment by sblondel** [comment]
Added a section to the wiki: https://github.com/ORNL-Fusion/xolotl/wiki/Running-Xolotl#how-to-submit-parallel-jobs-with-slurm
