### ISSUE TITLE
Question about the Jacobian matrix builder

### ISSUE THREAD

**Issue by jianqixi** [ORNL-Fusion/xolotl#119]
I hope this is a good place to ask my question. I am currently developing one cluster dynamics code, similar to the purpose of Xolotl to predict the He bubble evolution in materials. In my current code, I am using the Sundials dense matrix solver. I have a few questions that I want to ask for help. 

1. When developing the Xolotl code, how did you build the Jacobian matrix for the solver? Is it by hand-coding or using some external code to build? Currently, I am using the default method that the solver calls the ODE functions multiple times to build the Jacobian matrix, but this is a very time-consuming task. I need to improve it and build the Jacobian matrix by myself. 

2. In Xolotl code, when simulating the He bubbles, how large the bubble size can be predicted? In my current code, I have incorporated the grouping-size method, but the bubble size that I can predict is still less than 10 nm. After that, the code becomes pretty slow. I think the reason is that the time is cost when building the default Jacobian matrix by the solver. 

Any comments and suggestions on my above questions would be very appreciated!

**Comment by sblondel** [comment]
Hi @jianqixi ,
1. The Jacobian matrix is built by PETSc, the solver we are using. You give PETSc the list of entries that will be non-zero, the number of grid points, etc. , and it builds the object with the wanted sparsity (https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/solver/src/handler/PetscSolver1DHandler.cpp#L71 and https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/solver/src/handler/PetscSolver1DHandler.cpp#L133 for instance). I am not familiar with the Sundials solver so I don't know what would be equivalent. Then at each time step with compute the partial derivatives and pass them to PETSc to insert them in the Jacobian https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/solver/src/handler/PetscSolver1DHandler.cpp#L782 .
2. For the bubble size, even when using a grouping scheme you're going to be limited at one point by how big of a problem you can solve; an alternative method where the "group" goes to infinity is described in https://www.nature.com/articles/s41598-021-93542-9

**Comment by jianqixi** [comment]
Thank you for your clarification. For the first question, I wonder if the entries list that you provided to PETSc solver are the partial derivatives of the ODE? Or just provide the size of the ODE and then ask the PETSc to build the matrix by itself? Would you like to further clarify it for me? Thank you,

For the second one, I am very appreciated for the sharing of paper, it should be very useful. Thank you

**Comment by sblondel** [comment]
You provide the location of the partial derivatives within the Jacobian to PETSc. For instance, if cluster A and cluster B don't interact together, you don't need to keep an entry for it in the Jacobian because its value will always be 0.0. If they do interact, you let PETSc now that this entry needs to be active because its value will change. PETSc is in charge of mapping the entries to the Jacobian.

**Comment by jianqixi** [comment]
Thank you for your clarification, I see your points. For the sundials solver, I used a similar way to ask the Sundials solver to map the entries to Jacobian, but this process seems to be very time-consuming.
