### ISSUE TITLE
Error running benchmark

### ISSUE THREAD

**Issue by jlore** [ORNL-Fusion/xolotl#12]
I am trying to run the params_PSI2.txt benchmark, but it gives an error after 75 timesteps:

```
mpiexec -n 10 ~/XOLOTL/xolotl-build/xolotl params_PSI2.txt 

75 TS dt 0.002 time 0.032
Time: 0.03199999741738022
Helium content = 429.1373945691204
Deuterium content = 0
Tritium content = 0
Fluence = 12799.99896695209

xolotlSolver::Monitor1D: The surface is trying to go outside of the grid!!
Aborting.
```

**Comment by sblondel** [comment]
The error is normal, I added the documentation about it in the benchmark section. While doing it I noticed that the corresponding retention_PSI2.txt file was not up to date in master so I uploaded the new version.

**Comment by jlore** [comment]
Thanks, good to know it is expected.
