### ISSUE TITLE
PETSc "-plot_2d" doesn't work

### ISSUE THREAD

**Issue by wealthpanC** [ORNL-Fusion/xolotl#126]
When I add "-plot_2d" into input file,  no file was produced as you said.

**Comment by sblondel** [comment]
Have you build the code with the visualization libraries https://github.com/ORNL-Fusion/xolotl/wiki/Build-Configuration#visualization-library ?

**Comment by wealthpanC** [comment]
sorry, I have not! I try after building. Tnanks!

**Comment by wealthpanC** [comment]
sorry, I have not! I try after building. Thanks!

**Comment by wealthpanC** [comment]
Yes, I have build the code with the visualization, but there is  still no file you mentioned.

**Comment by sblondel** [comment]
@wealthpanC can you tell me which input file you are using? Have you tried any other "-plot" option? Our wiki needs to be updated on visualization I think.

**Comment by sblondel** [comment]
@wealthpanC This option for 1D runs is not supported anymore, see https://github.com/ORNL-Fusion/xolotl/wiki/PETSc-Options#1d-case for the current options.

**Comment by wealthpanC** [comment]
I want to know what will happen when the parameter “plot_series” works. I have used the latest parameters, but the results have not changed. Have I not installed the correct visualization?

**Comment by sblondel** [comment]
Sorry for the delay in replying, I discovered an issue when trying to use the "-plot_series" option. This option works in 1D and generates a plot every 10 TS showing the concentration as a function of depth for the first 18 clusters contained in the network (the indexing is arbitrary).

**Comment by wealthpanC** [comment]
How can I get the raw data for every TS, not a figure?

**Comment by sblondel** [comment]
Using the '-start_stop' option ( https://github.com/ORNL-Fusion/xolotl/wiki/PETSc-Options#1d-case ) will generate an HDF5 containing all the non negligible concentrations every time it is saved.
