### ISSUE TITLE
Error in compiling vtk-m

### ISSUE THREAD

**Issue by aoliaopaopao** [ORNL-Fusion/xolotl#127]
Hello, I reported an error when compiling vtk-m. Version 1.6.0 of vtk-m reported an error (. text+0x20): undefined reference to ` main '

[ 92%] Linking CXX executable CMakeLists
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
make[2]: *** [test/viz/CMakeLists] Error 1
make[1]: *** [test/viz/CMakeFiles/CMakeLists.dir/all] Error 2
make: *** [all] Error 2

**Comment by aoliaopaopao** [comment]
I checked build/test/viz/CMakeFiles/CMakeLists. dir/link Txt finds that the library file is missing. My content is

mpiicpc -O3 -DNDEBUG -DKOKKOS_DEPENDENCE -fopenmp -o CMakeLists  -Wl,-rpath,/software/xolotl/boost_1_73_0/lib:......

**Comment by sblondel** [comment]
@aoliaopaopao Xolotl uses the latest version of vtk-m which is 1.9.0.
