### ISSUE TITLE
Option for switching log level

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#128]
Add a runtime option to the parameter file to switch log level: 
- default: print in one file
- debug: print additional information in one file per rank

**Comment by PhilipFackler** [comment]
@sblondel, the levels are {debug, extra, info, warning, error}. The default level is "info". Would you rather enable per-rank logging on "extra" or "debug"?

**Comment by sblondel** [comment]
@PhilipFackler I guess starting at "extra".
