### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by liyujin1999** [ORNL-Fusion/xolotl#133]
When I build with CMake, I get the following error:
CMake Error at /public/home/yangqm/ustb/liyujin/plsm-stable/CMake/plsmConfig.cmake:29 (include):
  include could not find requested file:

    /public/home/yangqm/ustb/liyujin/plsm-stable/CMake/plsm.cmake
Call Stack (most recent call first):
  CMake/SetupPlsm.cmake:3 (find_package)
  CMake/SetupPlsm.cmake:10 (find_plsm)
  CMakeLists.txt:49 (include)

**Comment by sblondel** [comment]
plsm doesn't need to be build separately for Xolotl, see https://github.com/ORNL-Fusion/xolotl/wiki/Build-Configuration#plsm .

**Comment by liyujin1999** [comment]
> plsm doesn't need to be build separately for Xolotl, see https://github.com/ORNL-Fusion/xolotl/wiki/Build-Configuration#plsm .

Thank you very much. The problem has been solved
