### ISSUE TITLE
Compiler issue when using '-DXolotl_INCLUDE_RN_TPP_FILES=ON'

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#147]
In file included from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/impl/PSIReactionNetwork.tpp:10,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/PSIReactionNetwork.h:204,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/advection/SurfaceAdvectionHandler.h:6,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/advection/DummyAdvectionHandler.h:5,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/material/MaterialHandler.h:3,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/material/AlloyMaterialHandler.h:4,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/src/material/AlloyMaterialHandler.cpp:1:
/home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/impl/PSIReaction.tpp:18:1: error: redefinition of ‘template<class TRegion> double xolotl::core::network::getRate(const TRegion&, const TRegion&, double, double, double, double)’
   18 | getRate(const TRegion& pairCl0Reg, const TRegion& pairCl1Reg, const double r0,
      | ^~~~~~~
In file included from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/impl/AlloyReactionNetwork.tpp:5,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/AlloyReactionNetwork.h:98,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/flux/AlloyFitFluxHandler.h:11,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/material/AlloyMaterialHandler.h:3,
                 from /home/sophie/Workspace/xolotl-release-source/xolotl/core/src/material/AlloyMaterialHandler.cpp:1:
/home/sophie/Workspace/xolotl-release-source/xolotl/core/include/xolotl/core/network/impl/AlloyReaction.tpp:15:1: note: ‘template<class TRegion> double xolotl::core::network::getRate(const TRegion&, const TRegion&, double, double, double, double)’ previously declared here
   15 | getRate(const TRegion& pairCl0Reg, const TRegion& pairCl1Reg, const double r0,
      | ^~~~~~~
make[2]: *** [xolotl/core/CMakeFiles/xolotlCore.dir/build.make:202: xolotl/core/CMakeFiles/xolotlCore.dir/src/material/AlloyMaterialHandler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1404: xolotl/core/CMakeFiles/xolotlCore.dir/all] Error 2

**Comment by sblondel** [comment]
One solution is to rename each getRate method as getPSIRate, etc. @PhilipFackler Are there other options?

**Comment by PhilipFackler** [comment]
@sblondel, I was able to reproduce this error locally and fixed it with namespaces. Let me know if that works for you.

**Comment by sblondel** [comment]
It works.
