### ISSUE TITLE
Compiler error on Mac OS

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#148]
Undefined symbols for architecture arm64:

  "xolotl::core::network::ReactionNetwork<xolotl::core::network::ZrReactionNetwork>::setGridSize(unsigned int)", referenced from:

      vtable for xolotl::core::network::ReactionNetwork<xolotl::core::network::ZrReactionNetwork> in AlphaZrFitFluxHandlerTester.cpp.o

Probably have to extend the -DXolotl_INCLUDE_RN_TPP_FILES=ON approach for tests.

**Comment by PhilipFackler** [comment]
Looks like you need to add the conditional tpp include statement at the bottom of ZrReactionNetwork.h similar to AlloyReactionNetwork.h:
https://github.com/ORNL-Fusion/xolotl/blob/9edfcefec97cd2bf13f6791a08ffb7df999cf2d3/xolotl/core/include/xolotl/core/network/AlloyReactionNetwork.h#L97-L99
