### ISSUE TITLE
computeJacobian and Kokkos

### ISSUE THREAD

**Issue by liyujin1999** [ORNL-Fusion/xolotl#152]
Hello, why not use kokkos parallel processing when calculating the Jacobian matrix on all grids? Calculating the Jacobian takes up most of the program's time. The following is my rewriting on a single grid using the openmp parallel method of kokkos, but the execution time of this code will increase as the number of threads increases. I don't understand why, can you give me some advice?
Kokkos::parallel_for(dof-1, KOKKOS_LAMBDA(const int& i) {       
            MatStencil rowId01 = {0, 0, xi, i};            
            int pdColIdsVectorSize = reactionSize_view(i);    
            auto startingIdx = reactionStartingIdx_view(i);  
            MatStencil stencil_temp[pdColIdsVectorSize];
            for (int j=0; j<pdColIdsVectorSize; j++)
            {
                stencil_temp[j] = {0, 0, xi, reactionIndices_view(startingIdx+j)};
                reactingPartialsForCluster_view(j) = reactionVals_view(startingIdx + j);     
            }
            PetscErrorCode ierrSet;
            ierrSet = MatSetValuesStencil(J, 1, &rowId01, pdColIdsVectorSize, stencil_temp,
                        reactingPartialsForCluster_view.data(), ADD_VALUES);  
            checkPetscError(ierrSet, "PetscFunctions1D::computeDiagonalJacobian: MatSetValuesStencil (reactions) failed.");     
        });

**Comment by sblondel** [comment]
@liyujin1999 Thank you for your suggestion. We are in the process of updating the interface between Xolotl and PETSc by using a different method than `MatSetValuesStencil`, which makes the parallelization of setting the values in the Jacobian not relevant anymore.

**Comment by liyujin1999** [comment]
> @liyujin1999 Thank you for your suggestion. We are in the process of updating the interface between Xolotl and PETSc by using a different method than `MatSetValuesStencil`, which makes the parallelization of setting the values in the Jacobian not relevant anymore.

Hello, is there any problem with my above code logic? Why does the time increase as the number of threads increases?

**Comment by PhilipFackler** [comment]
It might have to do with this:
https://petsc.org/release/manual/getting_started/#cpu-openmp-parallelism
"Users can also put OpenMP pragmas into their own code. However since standard PETSc is not thread-safe, they should not, in general, call PETSc routines from inside the parallel regions."
