### ISSUE TITLE
Moving constant rate vector to view in the multi-instances

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#164]
Related to #143 .

In https://github.com/ORNL-Fusion/xolotl/blob/feature-multi-instances/xolotl/interface/src/XolotlInterface.cpp#L492 and https://github.com/ORNL-Fusion/xolotl/blob/feature-multi-instances/xolotl/core/src/network/ZrReactionNetwork.cpp#L85 .

**Comment by PhilipFackler** [comment]
@sblondel , you can test this
