### ISSUE TITLE
Multi instances for 800H (Alloy)

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#174]
@PhilipFackler The first step will be to decide how to divide the network for the sub-instances. Currently it uses 6 different types of clusters https://github.com/ORNL-Fusion/xolotl/blob/develop/xolotl/core/include/xolotl/core/network/AlloyTraits.h#L20 .

The 3 first ones are vacancies, the 3 last ones are interstitials, so as a first try I would split them this way (2 instances).

The way the input parameters work is that some of the values are used to generate both vacancies and interstitials in https://github.com/ORNL-Fusion/xolotl/blob/develop/xolotl/core/src/network/AlloyNetworkHandler.cpp#L17 

As an example, for a full network generated  with `netParam=50 50 0 6 4`, one sub-instance would have `netParam=50 50 0 6 0` and the other `netParam=50 0 0 0 4` (at the moment it would probably be a problem because the first `50` is used for `Perfect`, `Faulted`, and `Frank`, so these 3 would be double-counted).

**Comment by PhilipFackler** [comment]
@sblondel checkout the commit above. With this approach, classes encapsulate how the netParam is split among subinstances. AlphaZrSubOptions does what was being done before. AlloySubOptions does something like what you describe here. But, as you say, this won't work as it is. But we can now get netParam as a vector (we don't have to fake it with "maxD" etc). So, we could just use six values for this case and make it simpler. Anyway, let me know what you think.

This approach would also enable us to modify the subinstance options in other ways distinct to each material (if that would ever be necessary).

**Comment by sblondel** [comment]
@PhilipFackler That looks good. And yes it probably makes sense to have a more flexible way to set the network parameters for each type of material, not just in the context of multi-instances.

**Comment by sblondel** [comment]
@PhilipFackler For the output, currently the only thing we have is tailored for AlphaZr: https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/interface/src/Interface.cpp#L585 that mimics https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/solver/src/monitor/PetscMonitor0D.cpp#L558 .

Ideally the first method would know which type of network is used (from the material option maybe) and switch to https://github.com/ORNL-Fusion/xolotl/blob/stable/xolotl/solver/src/monitor/PetscMonitor0D.cpp#L487 automatically for the alloy case.

**Comment by PhilipFackler** [comment]
@sblondel that sounds like just adding this to the top of `XolotlInterface::outputData()`:

```c++
if (options->getMaterial() == "800H") {
    monitor::computeAlloy(...);
    return;
}
```
getting the TS, Vec, and IMonitor* from the solver.

But do we want this to happen more frequently than `outputData` is called from `MultiXolotl`?

**Comment by sblondel** [comment]
@PhilipFackler The thing is only the primary instance calls `outputData()' https://github.com/ORNL-Fusion/xolotl/blob/feature-extend-subinstance-params/xolotl/interface/src/MultiXolotl.cpp#L229 and it doesn't set the solver nor PETSc TS.

**Comment by PhilipFackler** [comment]
@sblondel Following up from yesterday's conversation, I'm thinking we parameterize [ReactionNetwork::getHeaderString](https://github.com/ORNL-Fusion/xolotl/blob/3d847a493153d6fd422c3b99e38a4a347c03d113/xolotl/core/include/xolotl/core/network/impl/ReactionNetwork.tpp#L368) so that it can produce the correct header on-demand. Then, have a function in the same place that will compute the values for a single line. The function name should be updated to reflect what this is for... something like `getMonitorDataHeaderString()` and `getMonitorData()`. Does this make sense? And is there a naming phrase that would be better?

**Comment by sblondel** [comment]
@PhilipFackler I think it makes sense, `getMonitorDataHeaderString()` would return a string and `getMonitorData()` a vector of double. When you say parameterize, do you mean each network type would have its implementation or could you have even multiple implementation for each network (not that we need it, I just wonder)?

**Comment by PhilipFackler** [comment]
Well, I originally meant function parameters that specify which values to get. But what you're suggesting would actually make more sense.

**Comment by sblondel** [comment]
I just thought of something else to take into account for `getMonitorData()`: it will have to work the same way whether it's 0D or 1D or more, and I guess the PETSc monitor or interface function will have to do the MPI reduce when needed.
