### ISSUE TITLE
Update README and Wiki

### ISSUE THREAD

**Issue by PhilipFackler** [ORNL-Fusion/xolotl#23]

**Comment by PhilipFackler** [comment]
First paragraph: "Xolotl also requires (partial) C++17 support, which is available since GCC 7.1..."

(not necessary)
Second paragraph: Maybe instead of using `/home/user`, we should put `$HOME` in the command-line examples. This would enable direct copy-paste for many commands.

Xolotl build command refers to `../xolotl-source`, should refer to `/home/user/xolotl-source`.

Boost
We don't require Boost.Timer in the new version.

**Comment by sblondel** [comment]
I think I have applied all the comments for the build configuration page in the attached file
[Build-Configuration.md](https://github.com/ORNL-Fusion/xolotl/files/6423434/Build-Configuration.md).
@PhilipFackler I'll update the README once you check this file one last time.

**Comment by PhilipFackler** [comment]
First two `cmake` examples under "Kokkos" should omit the `-DCMAKE_CXX_COMPILER=mpicxx`.

Last sentence under "PETSc": If the `PETSC_DIR` provided to the Xolotl configuration is the PETSc source directory (rather than the installation prefix), then you must specify the `PETSC_ARCH` variable as well.

**Comment by sblondel** [comment]
@PhilipFackler Thank you, can I ask you to look at one more file
[Guidelines.md](https://github.com/ORNL-Fusion/xolotl/files/6430105/Guidelines.md)
? Especially the Git section.

**Comment by PhilipFackler** [comment]
That looks good.
