### ISSUE TITLE
Introduce logging mechanism

### ISSUE THREAD

**Issue by PhilipFackler** [ORNL-Fusion/xolotl#30]
It would be useful to have a log file where we write extra information that we might want to see (especially in Debug mode), but that we don't want printed to the console.

Probably it would make the most sense to use Boost.Log since we already depend on boost.

**Comment by PhilipFackler** [comment]
As part of this, let's make separate "perf-log" file for timer/counter output. (All the info/iteration output can go to a general log file.) Printing to this file would append timing results. Then (especially useful for coupling case), we can re-structure things such that the interface can reset the timers after each solve and also keep track of running totals.

**Comment by bernhold** [comment]
We might want to check with @rothpc if there is any particular formatting for such a file that might facilitate its use with other tools and/or combining with performance data from other coupled components, etc.

**Comment by rothpc** [comment]
I'm not familiar with Boost's log library.  Looks like it is designed to give a C++ streams API similar to iostreams, but to make it easier to support filtering.  What I don't see on a quick scan is what the on-disk format is.  

From my perspective, the goals for such a capability include:
- Run-time control over whether logging is done at all.
- Fine-grained run-time control over logging from individual parts of the code.

Reader side:
- On-disk format that is (easily) machine parsable
- Existing C++ reader for the generated log files.
- Existing Python reader for the generated log files.

Some time in the future - it might be nice to have ability for to send performance data exposed via this log directly to another tool without touching the file system.  We don't generate that much performance data now, but it could be interesting in the future to do dynamic visualization that correlates the simulation data and the performance data.

**Comment by PhilipFackler** [comment]
@rothpc: The format is completely up to the user. In a previous job I used it with each "message" line prefixed with date/time, thread id, and log level.

I was thinking the general log file would look something like that (basically what gets printed to the console now). But the timers and counters would report to a separate file to make it easier to look at and compare. For that file, if there's already a de-facto conventional format to use, that would be nice. Otherwise, I don't expect it would be too difficult to code the reader(s) ourselves. That's assuming we're just reporting and/or plotting performance from xolotl. If we're talking about aggregating data from multiple codes, that's a whole different story...
