### ISSUE TITLE
Print git version info from code

### ISSUE THREAD

**Issue by PhilipFackler** [ORNL-Fusion/xolotl#39]
Use CMake to collect git version info and make it available to the code. Print code version at start-up (along with date/time, etc...).

At first this can simply be the commit hash. But this clears the way for version numbers when we're ready to start an actual release process.

**Comment by PhilipFackler** [comment]
@sblondel, I have this basically done. Let me know if you have suggestions about the formatting of the version info and the printed message.

**Comment by sblondel** [comment]
It all looks good to me.
