### ISSUE TITLE
Change main branch name

### ISSUE THREAD

**Issue by PhilipFackler** [ORNL-Fusion/xolotl#41]
Discuss names for new working git branches

**Comment by PhilipFackler** [comment]
Change "master" to "stable"

**Comment by sblondel** [comment]
Name was changed, here is how to update your local cloned repo:
git branch -m master stable
git fetch origin
git branch -u origin/stable stable
git remote set-head origin -a

**Comment by sblondel** [comment]
plsm-network branch was changed to develop, here is how to update your local repo:
git branch -m plsm-network develop
git fetch origin
git branch -u origin/develop develop
