### ISSUE TITLE
commandline flag that allows to ignore networkFile if it is missing

### ISSUE THREAD

**Issue by sblondel** [ORNL-Fusion/xolotl#64]
from @jguterl .
The aim is to be able to use the same parameter file for the initial run (no network file) and restart ones.

**Comment by sblondel** [comment]
@jguterl how about removing the networkFile option from the parameter file and specifying the network file name on the commandline when needed?

For instance: `xolotl/xolotl param_PISCES_He_75eV.txt --networkFile network_PISCES_He_75eV.h5` .

**Comment by jguterl** [comment]
Works too!
