### ISSUE TITLE
adding influx to retentionOut.txt

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/xolotl#66]
Adding influx per species to retentionOut will simplify analysis of implementation with time-varying flux (see picture below
![Screen Shot 2021-10-01 at 6 22 12 PM](https://user-images.githubusercontent.com/17376868/135699572-4023b7ec-5e7c-4be2-9f1f-886fb6035b8e.png)
)

**Comment by sblondel** [comment]
@jguterl Just to be sure I understand, you would want the instantaneous flux for each cluster listed in the `fluxDepthProfileFilePath` added to the `retentionOut.txt` file.

**Comment by sblondel** [comment]
yes, for each cluster species.

**Comment by sblondel** [comment]
A separate file "instantFlux.txt" is created because multiple cluster per species can have a generation term.

**Comment by jguterl** [comment]
Nice!
