### ISSUE TITLE
add maximum factor for time increase

### ISSUE THREAD

**Issue by jguterl** [ORNL-Fusion/xolotl#95]
Issue: increase of timestep too large by PETSC, results in very long timestep execution time.
Suggested solution: add a factor to limit the increase of the timestep: https://petsc.org/main/docs/manualpages/TS/TSAdaptSetClip.html

**Comment by jguterl** [comment]
issue solved by adding  "-ts_adapt_clip 0.1,1.1" to petsc options
Suggestion: adding that line in the wiki.
Reuse: can accelerate simulations by avoiding timesteps. Tradeoff between increase of dt and numbers of timesteps. No general recipe.

**Comment by sblondel** [comment]
@jguterl Thank you for finding the option, it has been added in: https://github.com/ORNL-Fusion/xolotl/wiki/PETSc-Options .
